### ISSUE TITLE
install issues 8.0.1 - leksah has grown too feature rich and too complicated

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#291]
i appreciate all the work which goes into leksah - i have used it since its beginning. today i am concerned about the direction it takes.
- leksah adds features which are beyond what most users need. these features are undocumented (the docs are in the state my group fixed them many years again!) and can, therefore, not be used.
- installation is a pain. i just spend a day to try to install leksah on 8.0.1 -- there are dependencies i do not see where they come from and what useable feature they support, but these dependencies make it impossible for a simple `cabal install leksah` to complete (this time it was `jsaddle`). the instructions are incomplete because leksah has grown too complex. 
- leksah is not a simple executable, it has dependencies which are not documented (on ghc and cabal version used for compilation). it is not possible to use a leksah built with one version of ghc for another one (for example, many required files are in .cabal/shared...)

i would suggest that a simpleLeksah is split off which includes the features which are documented and designed to assure that the executable is self contained. an advancedLeksah collects all the advanced features (which make installation so painful). [I know that this is an oversimplification as gtk is part of the issues and i appreciate the steps made to construct gi-gtk, which compiles in 8.0.1]. 

if leksah continues to add (undocumented) features and installation remains a problem, i will have to look elsewhere (as many of my colleagues have already). an IDE must be a reliable workshorse and loosing regularly days to reconstruct the IDE is not tolerable.

**Comment by hamishmack** [comment]
> installation is a pain. i just spend a day to try to install leksah on 8.0.1

I only installed GHC 8.0.1 myself on the weekend!  I have updated the metadata collection code and it seems to be working.  Porting Leksah to new versions of GHC is never easy because of GHC API stuff almost always requires fiddly changes.

The haskell-gi is stabilising and we should be able to start using the hackage version of haskell-gi.  I will update the github source and build instructions shortly.

If you know of any issues installing the current Hackage version of Leksah with GHC 7.10 please let me know as we should fix those ASAP.

> it is not possible to use a leksah built with one version of ghc for another one (for example, many required files are in .cabal/shared...)

The metadata collection will not work, but everything else should.  I used leksah compiled with GHC 7.10 to port it to 8.0.  It was annoying that I did not have metadata for GHC API of 8.0, but other than that it worked fine.  What sort of issues do you see?

**Comment by hamishmack** [comment]
I have pushed the latest haskell-gi and GHC 8 changes and updated the [build from github instructions](https://github.com/leksah/leksah#building-leksah-from-github).  This is still really new, but if you have time to check try it out it would be great.  Run `cabal update` before you start because I uploaded some of the packages to Hackage.

**Comment by jaccokrijnen** [comment]
I tried building with the new instructions, but when building `ltk` I get

```
Preprocessing library ltk-0.16.0.0...
[ 1 of 13] Compiling Graphics.UI.Frame.Rectangle ( src/Graphics/UI/Frame/Rectangle.hs, dist/dist-sandbox-17b9142/build/Graphics/UI/Frame/Rectangle.o )

src/Graphics/UI/Frame/Rectangle.hs:35:16:
    Module ‘GI.Gdk’ does not export ‘Rectangle(..)’

src/Graphics/UI/Frame/Rectangle.hs:35:31:
    Module ‘GI.Gdk’ does not export ‘rectangleWidth’

src/Graphics/UI/Frame/Rectangle.hs:35:47:
    Module ‘GI.Gdk’ does not export ‘rectangleHeight’

src/Graphics/UI/Frame/Rectangle.hs:35:64:
    Module ‘GI.Gdk’ does not export ‘rectangleX’

src/Graphics/UI/Frame/Rectangle.hs:35:76:
    Module ‘GI.Gdk’ does not export ‘rectangleY’

src/Graphics/UI/Frame/Rectangle.hs:35:88:
    Module ‘GI.Gdk’ does not export ‘rectangleReadWidth’

src/Graphics/UI/Frame/Rectangle.hs:35:108:
    Module ‘GI.Gdk’ does not export ‘rectangleReadHeight’

src/Graphics/UI/Frame/Rectangle.hs:35:129:
    Module ‘GI.Gdk’ does not export ‘rectangleReadX’

src/Graphics/UI/Frame/Rectangle.hs:35:145:
    Module ‘GI.Gdk’ does not export ‘rectangleReadY’
cabal: Leaving directory './vendor/ltk/'
```

Apparently the hackage version of `gi-gdk` bindings does not contain any source files since the 3.x releases.

**Comment by hamishmack** [comment]
Hi @jaccokrijnen, this is failing because you have a slightly older version of Gdk.  The CPP checks to detect this did not work (because the cabal version of the `gi-` packages no longer includes the pkg-config version).

I have pushed a fix to `ltk` and `leksah` that uses the pkc-config version to set CPP macros instead.

**Comment by jaccokrijnen** [comment]
Thanks, that was it, now it's building again! (I still don't get how the `gi-gdk` package on hackage can be empty though)

By they way, I did have to pass the flags manually (`-f -gdk318`, `-f -gtk-318`, `-f -gtk-320`). Otherwise, cabal would give me
```
cabal: The pkg-config package 'gdk-3.0' version >=3.18 is required but the
version installed on the system is version 3.16.7
```
Cabal is supposed to figure those flags out for me, right? Or should this be added to the build instructions.

**Comment by hamishmack** [comment]
> Thanks, that was it, now it's building again! (I still don't get how the gi-gdk package on hackage can be empty though)

All the source is generated now when it configures.  This means no one has to regenerate it manually and upload to Hackage for each minor Gtk+ update.

> Cabal is supposed to figure those flags out for me, right? Or should this be added to the build instructions.

Did you start from scratch?  I think it might fail if the package was already configured.  Certainly `cabal build` does not work (I think it runs configure again but with the same flags it worked out last time).  I think `cabal install` might fail too if the package was configured already.

**Comment by jaccokrijnen** [comment]
Yes, even from scratch. I've added #293

**Comment by JPMoresmau** [comment]
Rebuilding leksah and its dependencies is now a huge pain. jsaddle-dom takes at least an hour on my machine to build. Why is it needed? I don't do any JS in haskell.

**Comment by hamishmack** [comment]
I'm not against the idea of having more cabal flags for stripping stuff out (we already have -fyi).

`jsaddle-dom` replaces the `webkitgtk3` package for DOM manipulation in a WebKitGTK+ WebView (it is brought in as a dependency `ghcjs-dom`).  A lot of DOM functions are not exposed through the C interfaces in WebKitGTK+ and the solution was to do all the manipulation via JavaScriptCore instead.  There are a lot more functions now because it covers almost everything you can do in a browser with JS.

Currently `ghcjs-dom` is not used in Leksah very much at all yet, but I had hoped we could use it to:

* Make output pane interactive.  In particular it would be cool if we had something like the current `pretty-show` display that did not always force thunks and instead you could click on the unevaluated thunks to render them.  For instance you could show the first 50 items of lists, but leave a button for the tail that the user could click on to see more.

* Manipulate HTML in the Documentation.  I would like to make it easier to browse Haddock docs in Leksah and one thing that would be nice is if we could add an option to open the source in Leksah itself (instead of viewing the rendered HTML).

`haskell-gi`, `jsaddle-dom` and `ghcjs-dom` are in Hackage now and should be fairly stable going forward. I hope `cabal new-build` and `stack` will also help the build time issue, by making the number of "from scratch" builds rare.

**Comment by andrewufrank** [comment]
i just started with a fresh/clean 8.0.1 and did a fresh cabal, gtk2hs etc. 
i get the error msg:
gi-javascriptcore-4.0.4 failed during the configure step. The exception was:
user error ('/usr/bin/ghc' exited with an error:

/tmp/cabal-tmp-31739/gi-javascriptcore-4.0.4/dist/setup/setup.hs:3:1: error:
Failed to load interface for ‘Data.GI.CodeGen.CabalHooks’
Use -v to see a list of the files searched for.
)

i do not see what is wrong and what i can change.
--
it would be useful to have a simple leksah, which does not use and web interface, just gtk (gi-gtk is a great achievement) and nothing of the other more advanced (and undocumented) stuff, but would install without troubles.

**Comment by hamishmack** [comment]
I am not sure what has happened here.  It looks like it is not finding `haskell-gi` in the package repo.  Cabal should have installed it if it was not there.  Can you please try:

    cabal install haskell-gi

To see if that fixes it.

**Comment by hamishmack** [comment]
@andrewufrank thank you for your patience, it is very useful to find out about the issues.  It is annoying that our timezones do not overlap better.

**Comment by hamishmack** [comment]
@andrewufrank it might be nothing, but that is the wrong version of gi-javascriptcore in the error message.  Leksah needs `gi-javascriptcore-3.0.4` not `gi-javascriptcore-4.0.4`.  The reason it is important is that `gi-javascriptcore-3.0.4` is the WebKit1 API version and `gi-javascriptcore-4.0.4` is for WebKit2 API.  We are still using the WebKit1 API.

What was the command that produced the error?

Something like `cabal install gi-javasciprcore` then that would explain the difference in version numbers.  So try this instead:

    cabal install haskell-gi
    cabal install gi-javascriptcore-3.0.4

However if you were running a cabal install of leksah, then there might be a second issue (apart from not finding the `haskell-gi` module).   The upper bound of 3.1 in `jsaddle` should have prevented it choosing the wrong `gi-javascriptcore` package.  Could you please run it again with -v and post the logs here?

Thanks again in advance for helping us track this down.

**Comment by andrewufrank** [comment]
reading your explanation, i think it is likely that i used the -allow-newer flag. 
i tried many things but could not install gtk3 on a debian8-jessie system with ghc 8.0.1: there is an issue with cabal 1.24 and then the version of the base libraries (for example glib), where the filename in debian is not obvious nor the version installed. ghc 8. installed  on a debian9-stretch without problems, including gtk3. 
i understand that the problems with different versions are complex and hard to check - the earlier an installation checks for compatible versions of base libraries and documents them, the better. 

nevertheless, i think it would be valuable to have a small leksah (no web, no javascript, no advanced features, probably not even with a split and a server); this would reduce some problems with the installation (not with gi-gtk, which was my problem yestarday, i understand)

**Comment by andrewufrank** [comment]
i have given up on installing 8.0.1 on debian jessie and gone back. thus
i cannot try. i think i tried installing haskell-gi, but do not remember
what failed then.

-- 
Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
                 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil

**Comment by andrewufrank** [comment]
i will try later this week. thank you for pushing!

andrew

-- 
Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
                 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil

**Comment by andrewufrank** [comment]
i just tried with a (reasonably) clean debian jessie: 
i did 
cabal install Cabal cabal-install 
(gives version 1.24)
cabal install gi-gtk 
nstalled without problems.  - congratulations - much improved! (no gtk2hs-buildtools used!)
leksah does not install, it is limited to base < 4.9.0.0  
and ghc 8.0.1 comes with 4.9.0.0
can you fix leksah on hackage or on github. then i will continue

**Comment by hamishmack** [comment]
When you do **Step 4** in the [instructions](https://github.com/leksah/leksah#building-from-source) the command:

    cabal install ./ ./vendor/gi-gtk-hs ./vendor/ltk ./vendor/leksah-server ./vendor/haskellVCSGUI/vcsgui

It should get `vcsgui` from the submodule in the leksah git repository.  Git submodules are painful and are not updated automatically.  So if you skipped **Step 3** because you already had a clone of the git repo and just did a `git pull`, then the submodules may be out of date.  Check the status with:

    git status

If it looks like they are not up to date I think you can bring it up to date with:

    git submodule update

**Comment by andrewufrank** [comment]
your instructions are too complicated for me and most people that just want to use leksah. i tried to install leksah with --allow-newer flag and cabal install --allwo=newer alex happy gtk2hs-buildtools leksah works but fails for leksah server. i assume this is a minimal issue:
Building leksah-server-0.14.3.2...
Failed to install leksah-server-0.14.3.2
Build log ( /home/frank/.cabal/logs/leksah-server-0.14.3.2.log ):
cabal: Entering directory '/tmp/cabal-tmp-24643/leksah-server-0.14.3.2'
Configuring leksah-server-0.14.3.2...
Warning: 'ghc-options: -prof' is not necessary and will lead to problems when
used on a library. Use the configure flag --enable-library-profiling and/or
--enable-profiling.
Building leksah-server-0.14.3.2...
Preprocessing library leksah-server-0.14.3.2...
[ 1 of 15] Compiling Paths_leksah_server ( dist/build/autogen/Paths_leksah_server.hs, dist/build/Paths_leksah_server.o )
[ 2 of 15] Compiling IDE.Utils.Server ( src/IDE/Utils/Server.hs, dist/build/IDE/Utils/Server.o )

src/IDE/Utils/Server.hs:17:1-8: warning: [-Wtabs]
    Tab character found here, and in 39 further locations.
    Please use spaces instead.
[ 3 of 15] Compiling IDE.Core.CTypes  ( src/IDE/Core/CTypes.hs, dist/build/IDE/Core/CTypes.o )

src/IDE/Core/CTypes.hs:117:23-41: error:
    • Couldn't match type ‘ghc-boot-8.0.1:GHC.PackageDb.InstalledPackageInfo
                             PackageConfig.SourcePackageId
                             PackageConfig.PackageName
                             Module.UnitId
                             Module.ModuleName’
                     with ‘IPI.InstalledPackageInfo’
      NB: ‘IPI.InstalledPackageInfo’
            is defined in ‘Distribution.InstalledPackageInfo’
                in package ‘Cabal-1.24.0.0’
          ‘ghc-boot-8.0.1:GHC.PackageDb.InstalledPackageInfo’
            is defined in ‘GHC.PackageDb’ in package ‘ghc-boot-8.0.1’
      Expected type: PackageConfig -> PackageIdentifier
        Actual type: IPI.InstalledPackageInfo
                     -> Distribution.Package.PackageId
    • In the expression: IPI.sourcePackageId
      In an equation for ‘getThisPackage’:
          getThisPackage = IPI.sourcePackageId
cabal: Leaving directory '/tmp/cabal-tmp-24643/leksah-server-0.14.3.2'
cabal: Error: some packages failed to install:

if you could fix this, then leksah could be installed with a simple instruction on debian systems with 8.0.1. 
thank you!

**Comment by hamishmack** [comment]
If you find yourself using `--allow-newer` then something has probably already gone wrong and `--allow-newer` is unlikely to help.  Have you run `cabal update` recently?

> Building leksah-server-0.14.3.2...

What was the command that gave this output?  Was it the one in *Step 4*?

0.14.3.2 is an old version of leksah-server.  There is no way it will work with GHC 8.

Please check in `vender/leksah-server/leksah-server.cabal`.  If that is version 0.14.3.2 then have out of date git submodules.

If it says 0.16.0.0 in `vender/leksah-server/leksah-server.cabal` then for some reason cabal is ignoring the parameter `./vendor/leksah-server` when you run the command in *Step 4*.

**Comment by andrewufrank** [comment]
as i said - i was not following your stepts, which seem to complicated
to me and i thought i had installed leksah in 8.0.1 on another computer
with --allow-newer and nothing else and it worked.
leksah absoultely needs a method for painless installation (painless =
cabal install leksah and nothing else).

**Comment by jaccokrijnen** [comment]
I agree that there should be a painless installation on linux. We're planning to add .deb and .rpm installers to avoid these "from-source" builds for Leksah users.

**Comment by andrewufrank** [comment]
it would be sufficient if cabal install would work. at the moment i have the impression that neither of the 0.15.n versions of leksah-server can be build, because bin-package-db is not on hackage!
can you please upload?

**Comment by hamishmack** [comment]
bin-package-db was part of GHC 7.10, it does not exist in GHC 8.

**Leksah 0.15** works and is in Hackage, but does not compile with GHC 8.  If you use GHC 7.10 to compile Leksah 0.15, it should work.  After you install it you can put GHC 8 in your PATH and use Leksah 0.15 to work on projects that are building with GHC 8 (some metadata collection will probably fail to work properly so some features will not work well when working on GHC 8 projects).

**Leksah 0.16** is not finished, but you are welcome to try it.  You will need to follow the [instructions](https://github.com/leksah/leksah#building-from-source) to build it from github.

I am sorry Leksah 0.16 is taking so long to finish, but we have limited resources and we don't want to rush it.  In an ideal world we would have daily binary builds you could install to try out the latest version of Leksah 0.16.  I added some issues (the Ubuntu one is #297), but unless someone else has time to set it up we probably not get to it until after 0.16 is released.

**Comment by andrewufrank** [comment]
i use the a leksah which was compiled under 7.10 but the problem there is that one needs to use not only the leksah executable but also the files in .cabal that result from this build. this is non-inutitive; it would be long term desirable, if the necessary files (icons etc.) would be place in files in defined location, not in a subfolder of .cabal. i do not see why you go for leksah 0.16 when leksah 0.15 does not compile with ghc 8. 
i tried the method to install from source, but did not succeed. the libgirepository-1.0-dev cannot be installed under debian stretch (which is the place to start with ghc 8.0.1), because the underling gobject-introspection and gir1.2-glib-2.0 is already further (it should be 1.48.0.2-1, not i.42.0.2.2). 
could you make it to install. i report details in another post.
@jaccokrijnen: a deb install method would be nice, but other tools show that such .deb packages often lag long behind the current method. what is really needed is a **reliable** method to install leksah with cabal. (or at least a reliable and simple method to build from source).

**Comment by andrewufrank** [comment]
@hamishmack : i tried the method to install from source follwoing the instructions, but did not succeed.
first:  the libgirepository-1.0-dev cannot be installed under debian stretch (which is the place to start with ghc 8.0.1), because the underling gobject-introspection and gir1.2-glib-2.0 is already further (it should be 1.48.0.2-1, not i.42.0.2.2). i have 1.0.1 installed 
later i get :
`frank@udine:~/Workspace16/leksah-git/leksah$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: haskell-gi (user goal)
rejecting: haskell-gi-0.17.4 (conflict: requires pkg-config package
gobject-introspection-1.0>=1.32, not found in the pkg-config database)
rejecting: haskell-gi-0.17.3, haskell-gi-0.17.2, haskell-gi-0.17.1,
haskell-gi-0.17, haskell-gi-0.15, haskell-gi-0.14, haskell-gi-0.13,
haskell-gi-0.12, haskell-gi-0.11, haskell-gi-0.10.2, haskell-gi-0.10.1,
haskell-gi-0.10, haskell-gi-0.9, haskell-gi-0.8 (constraint from user target
requires ==0.17.4)
Dependency tree exhaustively searched.
`

i have pkg-config 0.29.4 installed.  what is missing

**Comment by hamishmack** [comment]
In that error message it says:

> requires pkg-config package gobject-introspection-1.0>=1.32, not found in the pkg-config database

You need to be able to run something like this:

```
$ pkg-config --modversion gobject-introspection-1.0
1.48.0
```

If it does not print out a version then it means it can't find `gobject-introspection-1.0.pc`.  This is a file provided the package `libgirepository-1.0-dev`.

> the libgirepository-1.0-dev cannot be installed under debian stretch

That sounds like it is the underlying issue.

> because the underling gobject-introspection and gir1.2-glib-2.0 is already further (it should be 1.48.0.2-1, not i.42.0.2.2). i have 1.0.1 installed

Not sure I understand this.  What error does `sudo apt-get install libgirepository-1.0-dev` give?

**Comment by andrewufrank** [comment]
the problem was with my sources.list file - i did not have a clean 
stretch installation. this is corrected now and leksah is compiling.
it stops at:
Preprocessing library gi-cairo-1.0.5...
Configuring gi-glib-2.0.5...
[1 of 1] Compiling Main             ( 
/home/frank/Workspace16/leksah-git/leksah/dist-newstyle/src/gi-cairo-1.0.5/dist/setup/setup.hs, 
/home/frank/Workspace16/leksah-git/leksah/dist-newstyle/src/gi-cairo-1.0.5/dist/setup/Main.o 
)

/home/frank/Workspace16/leksah-git/leksah/dist-newstyle/src/gi-cairo-1.0.5/dist/setup/setup.hs:3:1: 
error:
     Failed to load interface for ‘Data.GI.CodeGen.CabalHooks’
     Use -v to see a list of the files searched for.

what need to be fixed?

**Comment by jaccokrijnen** [comment]
What output do you get for
```
ghc-pkg list --package-db dist-newstyle/packagedb/ghc-VERSION
```
is haskell-gi in there?

I found Data.GI.CodeGen.CabalHooks was installed here:
```
$ ls dist-newstyle/build/haskell-gi-0.17.4/build/Data/GI/CodeGen/ | grep CabalHooks
CabalHooks.dyn_hi
CabalHooks.dyn_o
CabalHooks.hi
CabalHooks.o
```
Can you check if it's in the same location for you?

**Comment by andrewufrank** [comment]
i found the hooks at the same location as you indicate. but the ghc-pkg list indicated that i should run check. here the output:
```
frank@udine:~/Workspace16/leksah-git/leksah$ ghc-pkg check --package-db dist-newstyle/packagedb/ghc-8.0.1 | grep haskell-gi
There are problems in package haskell-gi-0.17.4:
  dependency "file-embed-0.0.10-25bbdda6d40ada5d0c507ed52226ff675fe1c9876da9dd7032d1cd2740fd261f" doesn't exist
  dependency "mtl-2.2.1-73acc432434c4b2f9e3f6a41899e7704966183fd32dc7d095e7f7d4a28f0663e" doesn't exist
  dependency "pretty-show-1.6.10-1b4249b56db71afeefed074ff4ece82a41852c9ddfcba147a442967fc07e75c4" doesn't exist
  dependency "safe-0.3.9-bb81c9818a31e1a309a7711a722979a2496bee3434b4e397b67651d09754f52b" doesn't exist
  dependency "text-1.2.2.1-6dd39317d9d2e9eba7d59d829b9928808ea2c1766ae54e05604c3fc15d9af106" doesn't exist
  dependency "xdg-basedir-0.2.2-d4a1933d0d5a0df25cf4a59d6c68c41e7da6a1a8ef7db87602b60dbe58cfee1d" doesn't exist
  dependency "xml-conduit-1.3.5-b58f4b12d21a720e4b46c7cb69616774862dc2640d830991ef31e0b8293fa37e" doesn't exist
There are problems in package haskell-gi-base-0.17:
  dependency "text-1.2.2.1-6dd39317d9d2e9eba7d59d829b9928808ea2c1766ae54e05604c3fc15d9af106" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
haskell-gi-0.17.4
haskell-gi-base-0.17
gi-gtk-0.3.18.15
gi-gdk-0.3.18.15
gi-gdkpixbuf-0.2.32.15
gi-gio-0.2.46.15
gi-pango-0.1.38.15
gi-atk-0.2.18.15
gi-gobject-0.2.46.15
gi-glib-0.2.46.15
gi-cairo-0.1.14.15
```

**Comment by jaccokrijnen** [comment]
The `new-build` process uses a global store for hackage packages and a local store for local packages (like a sandbox with only add-sources). ghc-pkg thinks your local packages are broken because it does not know about the global store (which is at ~/.cabal/store/ghc-VERSION/package.db/). So running
```
$ ghc-pkg list --package-db dist-newstyle/packagedb/ghc-VERSION/ --package-db ~/.cabal/store/ghc-VERSION/package.db/
```
should not report any broken packages.

I don't understand why it can't find `Data.GI.CodeGen.CabalHooks`, I just tried building Leksah from git with a clean package database and had no problems. Can try to run `git submodule update` to make sure you have the newest versions of all local dependencies?
And you could you give the result of running  `cabal new-build -v` as it suggests, so we can see where it looks for `Data.GI.CodeGen.CabalHooks`?

**Comment by andrewufrank** [comment]
i attach here the output of cabal-new-build -v. it shows the output of ghc-okg as well. i hope it helps to identify the problem. 
thank you!
[leksah-1.txt](https://github.com/leksah/leksah/files/315583/leksah-1.txt)

**Comment by andrewufrank** [comment]
i finally got leksah 0.16 to compile and run. 

missing was 
`cabal install haskell-gi`
please add this to the instructions on [https://github.com/leksah/leksah#building-from-source] (https://github.com/leksah/leksah#building-from-source)

```
Step 2: Install tools

cabal install alex happy haskell-gi
```

what is the best method to have a shortcut for 
`leksah_datadir=`pwd` dist-newstyle/build/leksah-0.16.0.0/build/leksah/leksah`
handy?

(or could perhaps the reliance on datadir be removed? it would help for simpler installs and less dependencies when copying leksah from one computer to another)

**Comment by jaccokrijnen** [comment]
Thanks, I've added it to the readme.

(@hamishmack: I can only make sense of this if the `haskell-gi` executable was somehow needed, but for me it builds just fine without (`which haskell-gi` gives no path). Otherwise this would be installing the library in "old style" cabal build which shouldn't be available to "new style" builds)

**Comment by gdennie** [comment]
Is there a design document for LekSah?
Is there a reason for the an editor with a Client/Server architecture?
Just curious as I try to embrace Haskell.

**Comment by jaccokrijnen** [comment]
@gdennie There's the original (outdated) [manual](http://leksah.org/leksah_manual.pdf), and I've started a small readme about the architecture [here](https://github.com/leksah/leksah/blob/master/Contributing.md).

The only reason I've heard for the client-server architecture is that the ghc library used to crash and take down leksah with it. But this has never happened (to me). I think it would be good to combine `leksah` and `leksah-server` as some functionality is now scattered and it is harder to diagnose a problem in leksah-server.

**Comment by jaccokrijnen** [comment]
@hamishmack I have made a flag for the codemirror editor, this saves quite some dependencies (notably: lens).

**Comment by Evi1M4chine** [comment]
@andrewufrank:

Please stop poisoning the Haskell community with this damaging mindset.

If anything, you mean that it got too much just tacked on without considering the core architecture and doing things properly.
Like Windows ME, or Firefox(OS lol), for example.

The main perk of the Haskell community is making things that go the extra mile, even if it is mentally hard, to make something very emergent and elegant. Like Haskell itself.
_Not_ being exactly like e.g. Gnome/Apple developers, obsessed with “simplicity” (aka dumbing down and crippling) out of primitive unreflecting fear and being overwhelmed.

There is no such thing as “too” feature-rich. Not even too complicated. There is only too little emergence (and elegance). And too much knee-jerk mind-caging.

So this bug is at best ridiculous. Blaming others for one’s mind not being able to cope… Such an unacceptable arrogant self-centered abusive mindset…
I’ve simply had enough of being impaired left and right, by obsessive crippling due to fear and the inability to understand that simplifying is the dumbed-down version of improving emergence/elegance. From not being able to get a smartphone that still is an actual (non-locked-down) computer anymore, to feature removal in all desktop environments to losing internal organs because doing the non-idiot thing is “too advanced and complicated” even for “experienced” doctors. This bug is a sign that the Idiocracy starts to reach even the few left-over enclaves.

INB4 ”I didn’t read any of that, let alone wanted to understand it, because it attacked my ego and that’s all that matters, so I’ll call it off-topic, complain in some other way that it didn’t fit the $rule du jour, and cling even harder to the same mindset, banning everything else from my perceived existence. Even when following it would have made my life and everyone else’s much better too. Because we’re humans.”

**Comment by hamishmack** [comment]
@Evi1M4chine building Leksah on GHC 8 was in a very bad place back in May as it was undergoing a big refactor (moving from Gtk2Hs to haskell-gi).  @andrewufrank has often provides us with excellent feedback on the issues he has encountered when Leksah and I worry that others may simply suffer in silence.

I think the key take aways from this issue are that we need to continue to work on streamlining the installation of Leksah and take care to make sure that features added do not detract from the experience for those that do not need them.  If this is helped by having flags to disable features that are incomplete or detract in some way, then we should keep that option in mind.

I am going to close this issue before it becomes a distraction.
